openapi: 3.0.1
info:
  title: Charles O'Clock REST API
  description: Clock-in and clock-out
  version: 1.0.0
paths:
  /users/{uuid}/tags:
    post:
      operationId: ADD_TAG
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tag'
  /users/{uuid}:
    get:
      operationId: GET_USER_BY_ID
      parameters:
      - name: uuid
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /users:
    post:
      operationId: REGISTER
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PhoneNumber'
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
components:
  schemas:
    Tag:
      type: object
      description: Tag
    PhoneNumber:
      required:
      - phoneNumber
      type: object
      properties:
        phoneNumber:
          type: string
      description: Phone number
    User:
      required:
      - phoneNumber
      type: object
      properties:
        phoneNumber:
          $ref: '#/components/schemas/PhoneNumber'
      description: User
